
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='http_fdw',
    version='2020.5.0a0',
    description='Multicorn based HTTP client PostgreSQL foreign data wrapper',
    python_requires='==3.*,>=3.8.0',
    author='Shane R. Spencer',
    author_email='spencersr@gmail.com',
    packages=['http_fdw'],
    package_dir={"": "."},
    package_data={},
    install_requires=[],
)
